### ISSUE TITLE
Any pre-trained model

### ISSUE THREAD

**Issue by JuanruMaryGuo** [calico/solo#39]
Hi, I am wondering if there's any pre-trained model to start with. And I also would like to know if there's any open dataset in h5ad format so that I can run directly with your code.

Thank you in advance.

**Comment by njbernstein** [comment]
Hi there,

I don't have any pre-trained models because `solo` needs to be run from scratch for each experiment. `solo` generates in silico training data for each experiment. 

This [link](https://www.google.com/url?q=https://storage.googleapis.com/calico-website-mca-storage/kang_2017_stim_pbmc.h5ad&sa=D&source=hangouts&ust=1592323110378000&usg=AFQjCNHEDiUFvEYVK0qw0PQoSiQyg2UPXg) will download the `2s` dataset from kang et al in h5ad format. I'll make an issue to make a collab notebook to run `solo`

**Comment by JuanruMaryGuo** [comment]
Thank you!

**Comment by njbernstein** [comment]
I'm going to close this issue for now. @JuanruMaryGuo  please don't hesitate to reach out with any further issues
