### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by reykajayasinghe** [calico/solo#42]
Thanks for providing this resource.

I am running into the following error - 
MemoryError: Unable to allocate 1.66 TiB for an array with shape (6794880, 33538) and data type int64. 

I wonder how much space you recommend having available to run a sample using the raw 10X data set. 

Or do you recommend filtering our 10X objects and then using the filtered matrix to run solo?

Thanks for your help

**Comment by njbernstein** [comment]
Hi @reykajayasinghe 

If this is a 10x run you need to filter your cells first as ~ 6 million is not realistic for a basic 10x run. I'd recommend using the prefiltered matrix 10x provides or do the filtering yourself so that only cells with sufficient UMIs are fed into `solo`.

Let me know if you have any more questions.

Best,
Nick

**Comment by njbernstein** [comment]
Please reopen if you are still having issues
